baseURL = 'https://stijnba.lk/'
languageCode = 'en-us'
title = 'Stijn Balk'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Services"
    url = "/services"
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'